In [1]:
import pandas as pd
import numpy as np 
import warnings
warnings.filterwarnings('ignore')

In [2]:
df=pd.read_csv('advertising.csv')

In [3]:
df.head()

TV  Radio  Newspaper  Sales
0  230.1   37.8       69.2   22.1
1   44.5   39.3       45.1   10.4
2   17.2   45.9       69.3    9.3
3  151.5   41.3       58.5   18.5
4  180.8   10.8       58.4   12.9

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 200 entries, 0 to 199
Data columns (total 4 columns):
 #   Column     Non-Null Count  Dtype  
---  ------     --------------  -----  
 0   TV         200 non-null    float64
 1   Radio      200 non-null    float64
 2   Newspaper  200 non-null    float64
 3   Sales      200 non-null    float64
dtypes: float64(4)
memory usage: 6.4 KB


In [5]:
df.isna().sum()

TV           0
Radio        0
Newspaper    0
Sales        0
dtype: int64

In [6]:
X=df[['TV','Radio','Newspaper']]
y=df[['Sales']]

In [7]:
display(X.head())
display(y.head())

TV  Radio  Newspaper
0  230.1   37.8       69.2
1   44.5   39.3       45.1
2   17.2   45.9       69.3
3  151.5   41.3       58.5
4  180.8   10.8       58.4

Sales
0   22.1
1   10.4
2    9.3
3   18.5
4   12.9

In [8]:
X.shape , y.shape

((200, 3), (200, 1))

In [9]:
from sklearn.model_selection import train_test_split

In [10]:
X_train, X_test, y_train, y_test = train_test_split(X,y,test_size=0.3,random_state=101)

In [11]:
print(X_train.shape)
print(X_test.shape)
print(y_train.shape)
print(y_test.shape)

(140, 3)
(60, 3)
(140, 1)
(60, 1)


In [12]:
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_squared_error

In [13]:
lr1 = LinearRegression()
lr1

LinearRegression()

In [14]:
lr1.fit(X_train,y_train)
lr1

LinearRegression()

In [15]:
w=lr1.coef_
b=lr1.intercept_

In [16]:
print(w)
print(b)

[[ 0.04469599  0.1875657  -0.00032275]]
[3.15152677]


In [17]:
y_train_pred=lr1.predict(X_train)
y_train_pred[:5]

array([[15.2167967 ],
       [24.04824594],
       [ 6.7331761 ],
       [19.95960496],
       [13.88237508]])

In [18]:
display(X_train.head())
display(y_train.head())

TV  Radio  Newspaper
85   193.2   18.4       65.7
183  287.6   43.0       71.8
127   80.2    0.0        9.2
53   182.6   46.2       58.7
100  222.4    4.3       49.8

Sales
85    15.2
183   26.2
127    8.8
53    21.2
100   11.7

In [19]:
display(X_test.head())

TV  Radio  Newspaper
37    74.7   49.4       45.7
109  255.4   26.9        5.5
31   112.9   17.4       38.6
89   109.8   47.8       51.4
66    31.5   24.6        2.2

In [20]:
y_train_pred2=lr1.predict(X_test)
y_train_pred2[:5]

array([[15.74131332],
       [19.61062568],
       [11.44888935],
       [17.00819787],
       [ 9.17285676]])

In [21]:
display(y_test.head())

Sales
37    14.7
109   19.8
31    11.9
89    16.7
66     9.5

In [22]:
print('MSE:', mean_squared_error(y_train, y_train_pred))

MSE: 3.0088167761579943


In [23]:
ip = np.array([74.7,49.4,45.7]).reshape(1,3)
lr1.predict(ip)

array([[15.74131332]])